language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install coverage
  - pip install coveralls

script: nosetests

after_success:
  - coverage combine
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
